"""initial tables

Revision ID: f3137ab92b44
Revises: 
Create Date: 2026-06-10 21:52:37.008894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3137ab92b44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('actual_high', sa.Integer(), nullable=True),
    sa.Column('actual_low', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bias_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('model_source', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('temp_type', sa.String(), nullable=True),
    sa.Column('correction_degrees', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brier_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('model_source', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('temp_type', sa.String(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('improvement_pct', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('model_source', sa.String(), nullable=False),
    sa.Column('predicted_high', sa.Integer(), nullable=True),
    sa.Column('predicted_low', sa.Integer(), nullable=True),
    sa.Column('forecast_horizon_hrs', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kalshi_markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kalshi_market_id', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolves_at', sa.DateTime(), nullable=True),
    sa.Column('temp_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kalshi_market_id')
    )
    op.create_table('kalshi_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('yes_price', sa.Float(), nullable=True),
    sa.Column('no_price', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['kalshi_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('predicted_temp', sa.Float(), nullable=True),
    sa.Column('kalshi_price', sa.Float(), nullable=True),
    sa.Column('net_edge', sa.Float(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('models_agreed', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['kalshi_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('size_dollars', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['kalshi_markets.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('signals')
    op.drop_table('kalshi_prices')
    op.drop_table('kalshi_markets')
    op.drop_table('forecasts')
    op.drop_table('brier_scores')
    op.drop_table('bias_corrections')
    op.drop_table('actuals')
    # ### end Alembic commands ###
